enumerate_tautomer: true
tauto_engine: rdkit
enumerate_isomer: true
isomer_engine: rdkit
optimizing_engine: AIMNET
max_confs: 1
memory: 1
capacity: 1
patience: 40
opt_steps: 400
threshold: 0.5
k: 1
mpi_np: 28
gpu_idx: [0]
use_gpu: true
